name: Github Action Demo
on: [ push ]
jobs: 
  Test:
    runs-on: macOS-latest
    steps: 
      - uses: actions/checkout@v3
      - run: echo "the job was automatically triggered by a ${{ github.event_name }} event."
      - run: python3 main.py